### ISSUE TITLE
New Entity Discovered: Studio

### ISSUE THREAD

**Issue by LanternCode** [DMU-CTEC2902-1920/Sample-Text#38]
I have identified a new entity: Studio.

Basically a studio is a company that develops games.

The use of this entity would be similar to the use of the developer eneity.

Developer may be a part of a studio.

Game may have been created by a studio.

Studio has a name, logo and features all developers that it now employs and all games developed by the studio.

This missing entity, if implemented would bring in the following aspects: Add new studio page, search studios and show individual studio page.

So, how do we go about this new entity. Should we include the entity, or, maybe just mention it without actually making content for it? Give your opinions down below.

**Comment by JMasiano** [comment]
I think we should stick with Developer as an entity. According to oxford dictionary, Developer:  a person or a company that designs and creates new products, a software developer. If you have Developer (meaning company) as an entity - then I think you could have "Credits" as an attribute that lists the developers (not a repeating group - just text). Like developer for gameBlogger is SampleText and the credits are all the people that contributed and their roles and what they did. Similarly in post movie credits you get credits listing the special effects teams, and music, and stage props teams etc...

**Comment by LanternCode** [comment]
I mean Studio as an additional entity. Developer would stay in. The thing is, some games are not made by single developers and are made by huge studios instead, we're talking about hundreds of people whom are all considered developers. A game is not made by the developers in the terms of ownership, it belongs to a studio. The credits you mention are basically GameDeveloper as a result as Many to Many relationship between Game and Developer.

**Comment by JMasiano** [comment]
Its a good idea but I was thinking to keep it simple for now. I suppose, since what you state is logically correct, it would be wrong to leave it out. But for now if we could assume 1 developer for each game it would make life simpler. If we have time we could upgrade the design to incorporate the the Studio table.  I'm just thinking of time constraints.

**Comment by zoemaestra** [comment]
^ what zeb said, and I mentioned this before briefly. I think we should ignore studio and just treat it as developers. Eg, if it's an indie game just name the dev but if it was made by a company then name the company as the developer. Otherwise we'll be out of our depth and getting distracted

**Comment by LanternCode** [comment]
Actually, now that you said it it makes perfect sense. A simple way around this is an inclusion of a boolean such as "isStudio" to add to the developer class/entity. Does that make GameDeveloper obsolete though? Two developers could be making an indie game and not be a studio.

**Comment by JMasiano** [comment]
@benjimaestro @LanternCode @mreman09 
Though lt Id mention that the ERD (pdf) was not available in the documents section for reference when I did this:
I agree. We would definitely make things more complicated. We could still get round this if we are allowed to add multiple developers, without losing the Developer table. Heres some provisional ideas (see below).As an idea, we could have it so that we add multiple developers, but it would change the flow of screens and require that we remember the ReviewNo and GameNo from one page to next.

Part of the ERD 

 [Game] (lists) [GameDeveloper] (is a) [Developer]

Flow from screen to screen
(each screen listing page attributes):

>>Start. Add Game Review Page
Instructions on what to do:
1. Add Game
2. Add Developer(s)
3. Add Review
4. View the Game Review Page
click next>>

>> 1. Add Game Page
(This screen is passed ReviewNo)
Upload Game Image:
Add Game Name:
Add Game details etc...
click next>>

>>2. Add Game Developers Page
(This screen is passed ReviewNo, GameNo)
Studio Name: (default is NA in database unless you add one)
Can be used for logic later to make Studio Name visible or not on form (invisible if Studio= NA).
Instructions: You can add more than one developer.
Developer Name:
Developer Address:
Developer LogoURL:
Add Developer details etc...
Add Developer Button (adds to Game Developers ListBox and clears developer details so another one can be added)
Game Developers ListBox
click Next>>

>>3. Add Review Page
Add the review here 
click Next>>

>>4. Game Review Page
View the completed game review and make amendments
click Finish>>
